# Generated by Django 4.2 on 2023-04-28 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('binance_api', '0002_crypto_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='change_24h',
            field=models.DecimalField(decimal_places=10, default='100', max_digits=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='name',
            field=models.CharField(default='hey', max_length=50),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='price',
            field=models.DecimalField(decimal_places=10, default='100', max_digits=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='symbol',
            field=models.CharField(default='hey', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='volume',
            field=models.DecimalField(decimal_places=10, default='100', max_digits=20),
        ),
        migrations.CreateModel(
            name='Favorite_crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='binance_api.crypto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'crypto')},
            },
        ),
    ]
